name: 'Build PSF (Docker) Image'
description: 'Builds a PSF/BFF Docker image (a deployable service)'
author: 'Peachjar Engineering'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  imageName:
    required: false
    description: When present, override the name of the image
  skipIntegrationTests:
    required: false
    description: If true, integration tests should not be ran in the container.
    default: false
  extraBuildArgs:
    required: false
    description: JSON string of extra build args to include when building.
    default: '{}'
outputs:
  image:
    description: Full docker image (with registry)
